In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Purchase data.xlsx to Purchase data.xlsx


In [ ]:
import pandas as pd
import numpy as np
import io
df = pd.read_excel(io.BytesIO(uploaded['Purchase data.xlsx']))
df.set_index('Customer', inplace=True)
df
Candies= df["Candies (#)"]
Mangoes = df["Mangoes (Kg)"]
Milk_Packets = df["Milk Packets (#)"]
Payment = df["Payment (Rs)"]
A = np.column_stack((Candies, Mangoes, Milk_Packets))
C = Payment.values
pseudo_inv = np.linalg.pinv(A)
X = pseudo_inv.dot(C)
rank_A = np.linalg.matrix_rank(A)
print(A)
print("The dimensionality of the vector space is the rank of the matrix")
print("The number of vectors in this vector space are ",rank_A)
print("Rank of A:", rank_A)
print("The cost of each product are ",X,"respectively.")

[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
The dimensionality of the vector space is the rank of the matrix
The number of vectors in this vector space are  3
Rank of A: 3
The cost of each product are  [ 1. 55. 18.] respectively.


In [ ]:
df['Customer Status'] = np.where(Payment > 200, 'Rich', 'Poor')

# Display the updated DataFrame
#print(df)
df

Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
Customer                                                              
C_1                20             6                 2           386   
C_2                16             3                 6           289   
C_3                27             6                 2           393   
C_4                19             1                 2           110   
C_5                24             4                 2           280   
C_6                22             1                 5           167   
C_7                15             4                 2           271   
C_8                18             4                 2           274   
C_9                21             1                 4           148   
C_10               16             2                 4           198   

         Customer Status  
Customer                  
C_1                 Rich  
C_2                 Rich  
C_3                 Rich  
C_4                 Poor  
C_5                 Rich  
C_6                 Poor  
C_7                 Rich  
C_8                 Rich  
C_9                 Poor  
C_10                Poor